Apply:
  Enabled: true
  Password: Toastbrot
  Defaultgroup: default
  Group: Member
  Freeze: false
  Mute: false
  KickWrongPW: false
  BlockPWinChat: false
Time:
  Enabled: false
  Group: false
  Time: 10
  CountOffline: false
Ranks:
- Admin,5
PromoteSyntax: none
